import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: ['tests/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'json-summary'],
      reportsDirectory: './coverage',
      include: ['src/**/*.ts'],
      exclude: [
        'src/**/*.d.ts',
        'src/scripts/**/*.ts',
        'src/index.ts',
        'src/worker.ts',
        'src/auth/**/*.ts',
        'src/db/migrate.ts',
        'src/observability/metricsServer.ts',
        'src/orchestrator/memory.ts',
        'src/orchestrator/schedulerQueue.ts',
        'src/routes/approvals.ts',
        'src/routes/audit.ts',
        'src/routes/auth.ts',
        'src/routes/billing.ts',
        'src/routes/index.ts',
        'src/routes/knowledge.ts',
        'src/routes/messages.ts',
        'src/services/billing.ts',
        'src/services/email.ts',
        'src/services/embeddingBackfill.ts',
        'src/services/knowledge.ts',
        'src/services/notifications.ts',
        'src/services/outgoingWebhooks.ts',
        'src/services/retrievalMetrics.ts',
        'src/services/templateMarketplace.ts',
      ],
    },
  },
});
